name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    
    - name: update and upgrade
      run: sudo apt-get update -y && sudo apt upgrade -y

    - name: Install gtk3 for devs
      run: sudo apt-get install -y libgtk-3-dev

    - name: Install dependencies
      run: make
